config/routes.rb
TwitterApp::Application.routes.draw do

  devise_for :users , :path_prefix => 'devise'
  resources :users

  root :to => 'home#index'

  get 'bio' => 'home#bio'
  get 'tweets' => 'home#tweets'
  get 'home' => 'home#index'
  post 'trend' => 'trends#create'

 end

app/models/trend.rb
class Trend < ActiveRecord::Base

  attr_accessible :name, :url

  has_and_belongs_to_many :users

end

app/models/tweet.rb
class Tweet

  attr_accessor :name, :created_at, :text, :user_id, :tweet_id

  def initialize(name, created_at, text, user_id, tweet_id)
    @name = name
    @created_at = created_at
    @text = text
    @user_id = user_id
    @tweet_id = tweet_id
  end

end

app/models/twitter.rb
require 'oauth'
require 'rubygems'
require 'trend'
require 'tweet'
require 'uri'

class Twitter

  def initialize
    @configuration = YAML.load(File.open('config/configuration.yml'))['client']
  end

  # Queries and returns the trendings topic of twitter
  #
  # @return [Array] with the information of the trending topics
  def trending_topics
    response = access_token.
       request(:get,
               @configuration['base_url_v'] + 'trends/place.json?id=' + @configuration['woeid'])
    response_json = JSON.parse(response.body)
    response_json[0]['trends'].map do |trend|
      Trend.new(trend.slice('name', 'url'))
    end
  end

  # Searches and returns the most recent tweets
  #
  # @param hashtag [String] the hashtag to consult
  # @param n [Fixnum] the number of tweets
  #
  # @return [Array] with the information of the tweets
  def tweets(hashtag, n)
    response = access_token.
       request(:get, URI.encode(@configuration['base_url_v'] +
                                "search/tweets.json?q=#{hashtag}&count=#{n}"))
    response_json = JSON.parse(response.body)
    response_json['statuses'].map do |status|
      Tweet.new(status['user']['name'], status['created_at'],
                status['text'], status['user']['id'], status['id'])
    end
  end

  # Queries and returns the relevant information of a user.
  #
  # @param name [String] the twitter name of the user
  #
  # @return [Hash] with the relevant information of the user
  def bio(name)
    response = access_token.
        request(:get,
                URI.encode(@configuration['base_url_v'] + "users/show.json?screen_name=#{name}"))
    response_json = JSON.parse(response.body)
    TwitterUser.new(response_json['name'], response_json['description'])
  end

  # Sets the authentication to perform queries
  #
  # @return [OAuth::AccessToken]
  private
  def access_token
    consumer = OAuth::Consumer.
        new(@configuration['client_id'], @configuration['client_secret'],
            {site:  @configuration['base_url'], scheme: :header})

    token_hash = { oauth_token: @configuration['oauth_token'],
                   oauth_token_secret: @configuration['oauth_token_secret'] }

    OAuth::AccessToken.from_hash(consumer, token_hash)
  end

end

app/models/twitter_user.rb
class TwitterUser

  attr_accessor :name, :description

  def initialize(name, description)
    @name = name
    @description = description
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin

  has_and_belongs_to_many :trends

  # Adds a trend to a user. In case that the trend exist adds that instance.
  # Otherwise crates a new trend with the name and url passed and associates to the user.
  #
  # @param string [name] the name of the trend
  # @param string [url] the url of the trend
  #
  # @return [boolean] true if no exists already a trend in the users trend list, with the same
  # name and url. Otherwise returns false
  def add_trend(name, url)
    trend_exists =  User.joins(:trends).where('email = ? AND trends.name = ? AND trends.url = ?',
                                       self.email, name, url)
    if trend_exists.empty?
      trend = Trend.where('name = ? AND url = ?', name, url).first
      if (trend.nil?)
        trend = Trend.new(name: name, url: url)
      end
      self.trends << trend
      trend
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  def after_sign_in_path_for(resource)
    if resource[:admin]
      users_path
    else
     super
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :init

  def index
    @list_trending = @twitter.trending_topics
  end

  def tweets
    @list_tweets = @twitter.tweets(params[:trend_name] , 10)
  end

  def bio
    @user = @twitter.bio(params[:tweet_owner])
  end

  private
  def init
    @twitter = Twitter.new
  end

end

app/controllers/trend_controller.rb
class TrendController < ApplicationController

  def create
    trend = current_user.add_trend(params[:name], params[:url])
    if trend.nil?
      respond_to do |format|
        format.json {render json:  {errors: 'You already have the trending topic'}, status: 422 }
      end
    else
      respond_to do |format|
        format.json  {render json: trend , status: 200}
      end
    end
  end

end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController

  def create
    trend = current_user.add_trend(params[:name], params[:url])
    if trend.nil?
      respond_to do |format|
        format.json {render json:  {errors: 'You already have the trending topic'}, status: 422 }
      end
    else
      respond_to do |format|
        format.json  {render json: trend , status: 200}
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_role

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
   @user = User.new
   respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to(users_path)
  end

  private
  def check_role
    redirect_to home_path unless current_user.admin
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-warning" role="alert">
        #{sentence}
        #{messages}
       </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/home/bio.html.erb
<div class="container">

  <div class="page-header">
    <h1>Biography for: <small> <%= params[:tweet_owner] %></small></h1>
  </div>

  <table class="table table-condensed">
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>

    <tr>
      <td><%= @user.name.presence || 'No name.' %></td>
      <td><%= @user.description.presence || 'No Description.' %></td>
    <tr>
  </table>

  <div>
    <%= link_to 'back', tweets_path(trend_name: params[:trend_name]) %> |
    <%= link_to 'home', home_path %></td>
  </div>

</div>

app/views/home/index.html.erb
<div class="container">

  <div class="page-header">
    <h1>Twitter: <small>Trendings topics</small></h1>
  </div>

  <table class="table table-condensed">
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th></th>
      <th></th>
    </tr>

    <% @list_trending.each do |trend| %>
      <tr>
        <td><%= trend.name %></td>
        <td><%= trend.url %></td>
        <td><%= link_to 'Tweets for trending topics', tweets_path(trend_name: trend.name) %></td>
        <td class="trendLine" data-name="<%= trend.name %>"
            data-url="<%= trend.url %>">Add Favorites</td>
      </tr>
    <% end %>
  </table>

  <h1><small>My favorites Trendings topics</small></h1>

  <table class="table table-condensed" id="favorites_table">
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th></th>
      <th></th>
    </tr>

    <% current_user.trends.each do |trend| %>
      <tr>
        <td><%= trend.name %></td>
        <td><%= trend.url %></td>
      </tr>
    <% end %>

  </table>

</div>

app/views/home/tweets.html.erb
<div class="container">

  <div class="page-header">
    <h1>Tweets for: <small><%= params[:trend_name] %></small></h1>
  </div>

  <table class="table table-condensed">

    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Information</th>
    </tr>

    <% @list_tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.name %></td>
        <td><%= tweet.created_at %></td>
        <td><%= tweet.text %></td>
        <td><%= link_to 'View user biography',
                        bio_path(tweet_owner: tweet.name, trend_name: params[:trend_name]) ,
                        class: 'btn-link' %></td>
      </tr>

    <% end %>

    <td><%= link_to 'back', home_path, class: 'btn-link' %></td>

  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link' %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link'  %> |
      <%= link_to 'Login', new_user_session_path, class: 'navbar-link'  %>
    <% end %>
  </p>

  <% if user_signed_in? && current_user.admin %>
    <ul class="nav nav-pills">
      <li role="New" >
        <%= link_to 'New User', new_user_path, class: 'navbar-link'  %>
      </li>
      <li role="list" >
        <%= link_to 'Users', users_path, class: 'navbar-link'  %>
      </li>
    </ul>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user,  html: {class: 'table form-horizontal'}) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-warning" role="alert">
      <%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <% if @validatable %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <div class="col-sm-6">
      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admin, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.check_box :admin %></li>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Editing User</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <div class="page-header">
    <h1><small>Users: </small></h1>
  </div>

    <table class="table table-striped">
      <tr>
        <th>Email</th>
        <th>Rol</th>
        <th></th>
        <th></th>
      </tr>

      <% @users.each do |user| %>
        <tr>
            <td><%= user.email %></td>
            <% if user.admin %>
                <td>Admin</td>
            <% else %>
                <td>User</td>
            <% end %>

          <td><%= link_to 'Remove User', user, method: :delete, data: { confirm: 'Are you sure?' },
                         class: 'btn-link'  %></td>
          <td><%= link_to 'Edit User', edit_user_path(user), class: 'btn-link' %></td>
        </tr>
      <% end %>

    </table>

    <div>
      <%= link_to 'back', home_path %></td>
    </div>
</div>

app/views/users/new.html.erb
<h2>Create User</h2>

<%= render 'form' %>

<%= link_to 'Back', home_path %>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <table class="table table-condensed">
    <tr>
      <th>Email</th>
      <th>Rol</th>
      <th></th>
    </tr>

    <tr>
      <td><%= @user.email %></td>
        <% if @user.admin %>
          <td>Admin</td>
        <% else %>
          <td>User</td>
        <% end %>
      <td><%= link_to 'Edit User', edit_user_path(@user), class: 'btn-link' %></td>
    </tr>

  </table>

  <%= link_to 'Back', users_path %>
</div>